# Generated by Django 4.0.2 on 2022-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('publish_date', models.DateField()),
                ('bid_ends', models.DateField()),
                ('image', models.ImageField(default='', upload_to='auctions/images')),
            ],
        ),
    ]
