# Generated by Django 4.0.2 on 2022-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
